In [7]:
import numpy as np
np.random.seed(123) #seed for reproducibility

x1 = np.random.randint(10, size=6) #1D
x2 = np.random.randint(10, size=(3, 4)) #2D
x3 = np.random.randint(10, size=(3, 4, 5)) #3D
#1. ATTRIBUTES OF ARRAYS:
print("x3 ndim: ", x2.ndim)
print("x3 shape:", x2.shape)
print("x3 size: ", x2.size)

x3 ndim:  2
x3 shape: (3, 4)
x3 size:  12


In [8]:
print(x2)

[[6 1 0 1]
 [9 0 0 9]
 [3 4 0 0]]


In [9]:
print("dtype:", x3.dtype)

dtype: int32


In [10]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [14]:
#2.INDEXING OF ARRAYS:
x1

array([2, 2, 6, 1, 3, 9])

In [13]:
x1[0]

2

In [16]:
x1[-2]

3

In [17]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [18]:
x2[0,0]

6

In [19]:
x2[2, -1]

0

In [20]:
x2[-2, -1]

9

In [21]:
x2[0, 2] = 5

In [22]:
x2

array([[6, 1, 5, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [24]:
#3.SLICING ARRAYS:
#x[start:stop:step]
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y[:5]

array([0, 1, 2, 3, 4])

In [26]:
y[4:7]

array([4, 5, 6])

In [27]:
y[::2]

array([0, 2, 4, 6, 8])

In [28]:
y[1::2]

array([1, 3, 5, 7, 9])

In [29]:
y[::-1]#all elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
y[5::-2]

array([5, 3, 1])

In [31]:
x2

array([[6, 1, 5, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [32]:
x2[:2, :3]

array([[6, 1, 5],
       [9, 0, 0]])

In [33]:
x2[:, ::2]

array([[6, 5],
       [9, 0],
       [3, 0]])

In [34]:
x2[:, 2]

array([5, 0, 0])

In [35]:
x2[0, :]

array([6, 1, 5, 1])

In [36]:
x2[0]

array([6, 1, 5, 1])

In [39]:
x2_sub = x2[:, ::2]
x2_sub


array([[6, 5],
       [9, 0],
       [3, 0]])

In [40]:
x2_sub[0, 0] = 18
x2

array([[18,  1,  5,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [41]:
x2_sub = x2[:2, :2].copy()
x2_sub

array([[18,  1],
       [ 9,  0]])

In [43]:
x2_sub[0,1] =15
x2_sub

array([[18, 15],
       [ 9,  0]])

In [44]:
x2

array([[18,  1,  5,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [46]:
#4.RESHAPING OF ARRAYS:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
z = np.array([1, 2, 3])
z.reshape((1, 3))

array([[1, 2, 3]])

In [49]:
z.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [50]:
z[np.newaxis, :]

array([[1, 2, 3]])

In [51]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [58]:
#ARRAY CONCATENEATION AND SPLITTING:
x = np.array([1, 2, 3])
np.concatenate([x, y, z])

array([1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

In [54]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [59]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.hstack([z, grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [68]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 4])
print(x1, x2, x3)

[1 2 3] [99] [99  3  2  1]


In [62]:
np.split?


In [65]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [77]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
